# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37d89ab2b73ff30319aedbf9b0313835f04afbe3e4b5ac717a518ce5f279c677560ba4251c7144cfa9a674493b33faac46813c2d4248027cd4888db6fbe7d9ea

test:
  secret_key_base: 0c645560e4a44d6745de5ba633b069be07161e9f8fd8107b15afffbb92399483e1b10a0f87a764acc4323e49c644652a2f813b814ef88058324a602e24170026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
